name: Build Android APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Generate release keystore
      run: |
        mkdir -p android/app/keystore
        keytool -genkey -v -keystore android/app/keystore/release.keystore \
          -alias vibenest -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass vibenest2024 -keypass vibenest2024 \
          -dname "CN=VibeNest, OU=Mobile, O=VibeNest, L=City, S=State, C=US"
      
    - name: Build Android Release APK
      working-directory: ./android
      env:
        RELEASE_STORE_FILE: app/keystore/release.keystore
        RELEASE_STORE_PASSWORD: vibenest2024
        RELEASE_KEY_ALIAS: vibenest
        RELEASE_KEY_PASSWORD: vibenest2024
      run: ./gradlew assembleRelease --no-daemon
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vibenest-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
        body: |
          ## VibeNest Android APK
          
          **Installation:**
          1. Download app-release.apk
          2. Enable "Install from Unknown Sources" in Android settings
          3. Open the APK to install
          
          **Features:**
          - Optimized release build (smaller size, faster installation)
          - Mobile authentication with system browser
          - Full story sharing functionality
          - Like, comment, and bookmark features
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
